-- Auto-generated by scripts/build_riftbound_collation.py
-- Source: /Users/josh/Dev/bridge-ai-to-tts/workspaces/riftbound/objects/p0035__c2d323__riftbound-cardlibrary/script.lua

SFD_Common_Pool = {"SFD-001","SFD-002","SFD-003","SFD-004","SFD-005","SFD-006","SFD-007","SFD-008","SFD-009","SFD-010","SFD-031","SFD-032","SFD-033","SFD-034","SFD-035","SFD-036","SFD-037","SFD-038","SFD-039","SFD-040","SFD-061","SFD-062","SFD-063","SFD-064","SFD-065","SFD-066","SFD-067","SFD-068","SFD-069","SFD-070","SFD-091","SFD-092","SFD-093","SFD-094","SFD-095","SFD-096","SFD-097","SFD-098","SFD-099","SFD-100","SFD-121","SFD-122","SFD-123","SFD-124","SFD-125","SFD-126","SFD-127","SFD-128","SFD-129","SFD-130","SFD-151","SFD-152","SFD-153","SFD-154","SFD-155","SFD-156","SFD-157","SFD-158","SFD-159","SFD-160","SFD-207"}
SFD_Uncommon_Pool = {"SFD-011","SFD-012","SFD-013","SFD-014","SFD-015","SFD-016","SFD-017","SFD-018","SFD-041","SFD-042","SFD-043","SFD-044","SFD-045","SFD-046","SFD-047","SFD-048","SFD-071","SFD-072","SFD-073","SFD-074","SFD-075","SFD-076","SFD-077","SFD-078","SFD-101","SFD-102","SFD-103","SFD-104","SFD-105","SFD-106","SFD-107","SFD-108","SFD-131","SFD-132","SFD-133","SFD-134","SFD-135","SFD-136","SFD-137","SFD-138","SFD-161","SFD-162","SFD-163","SFD-164","SFD-165","SFD-166","SFD-167","SFD-168","SFD-208","SFD-209","SFD-210","SFD-211","SFD-212","SFD-213","SFD-214","SFD-215","SFD-216","SFD-217","SFD-218","SFD-219","SFD-220","SFD-221"}
SFD_Rare_Pool = {"SFD-019","SFD-020","SFD-021","SFD-022","SFD-023","SFD-024","SFD-025","SFD-026","SFD-049","SFD-050","SFD-051","SFD-052","SFD-053","SFD-054","SFD-055","SFD-056","SFD-079","SFD-080","SFD-081","SFD-082","SFD-083","SFD-084","SFD-085","SFD-086","SFD-109","SFD-110","SFD-111","SFD-112","SFD-113","SFD-114","SFD-115","SFD-116","SFD-139","SFD-140","SFD-141","SFD-142","SFD-143","SFD-144","SFD-145","SFD-146","SFD-169","SFD-170","SFD-171","SFD-172","SFD-173","SFD-174","SFD-175","SFD-176","SFD-181","SFD-183","SFD-185","SFD-187","SFD-189","SFD-193","SFD-195","SFD-199","SFD-201","SFD-203","SFD-205"}
SFD_Epic_Pool = {"SFD-027","SFD-028","SFD-029","SFD-030","SFD-057","SFD-058","SFD-059","SFD-060","SFD-087","SFD-088","SFD-089","SFD-090","SFD-117","SFD-118","SFD-119","SFD-120","SFD-147","SFD-148","SFD-149","SFD-150","SFD-177","SFD-178","SFD-179","SFD-180","SFD-182","SFD-184","SFD-186","SFD-188","SFD-190","SFD-191","SFD-192","SFD-194","SFD-196","SFD-197","SFD-198","SFD-200","SFD-202","SFD-204","SFD-206"}
SFD_Showcase_Pool = {"SFD-020a","SFD-026a","SFD-028a","SFD-029a","SFD-050a","SFD-054a","SFD-057a","SFD-058a","SFD-082a","SFD-085a","SFD-088a","SFD-089a","SFD-110a","SFD-113a","SFD-119a","SFD-120a","SFD-141a","SFD-143a","SFD-148a","SFD-149a","SFD-170a","SFD-171a","SFD-177a","SFD-180a","SFD-222","SFD-223","SFD-223s","SFD-224","SFD-224s","SFD-225","SFD-225s","SFD-226","SFD-227","SFD-227s","SFD-228","SFD-228s","SFD-229","SFD-230","SFD-230s","SFD-231","SFD-232","SFD-232s","SFD-233","SFD-233s","SFD-234","SFD-235","SFD-235s","SFD-236","SFD-236s","SFD-237","SFD-237s","SFD-238","SFD-239","SFD-239s","SFD-240","SFD-241","SFD-242","SFD-243","SFD-244","SFD-245","SFD-246","SFD-247","SFD-248","SFD-249","SFD-250","SFD-251"}
SFD_RarePlus_Roll = { { pool = "SFD_Rare_Pool", weight = 87.5 }, { pool = "SFD_Epic_Pool", weight = 12.5 } }
SFD_Any_Roll = { { pool = "SFD_Common_Pool", weight = 75 }, { pool = "SFD_Uncommon_Pool", weight = 22 }, { pool = "SFD_Rare_Pool", weight = 2.5 }, { pool = "SFD_Epic_Pool", weight = 0.4 }, { pool = "SFD_Showcase_Pool", weight = 0.1 } }

OGN_Common_Pool = {"OGN-001","OGN-002","OGN-003","OGN-004","OGN-005","OGN-006","OGN-007","OGN-008","OGN-009","OGN-010","OGN-011","OGN-012","OGN-013","OGN-014","OGN-042","OGN-043","OGN-044","OGN-045","OGN-046","OGN-047","OGN-048","OGN-049","OGN-050","OGN-051","OGN-052","OGN-053","OGN-054","OGN-055","OGN-083","OGN-084","OGN-085","OGN-086","OGN-087","OGN-088","OGN-089","OGN-090","OGN-091","OGN-092","OGN-093","OGN-094","OGN-095","OGN-096","OGN-124","OGN-125","OGN-126","OGN-127","OGN-128","OGN-129","OGN-130","OGN-131","OGN-132","OGN-133","OGN-134","OGN-135","OGN-136","OGN-137","OGN-165","OGN-166","OGN-167","OGN-168","OGN-169","OGN-170","OGN-171","OGN-172","OGN-173","OGN-174","OGN-175","OGN-176","OGN-177","OGN-178","OGN-206","OGN-207","OGN-208","OGN-209","OGN-210","OGN-211","OGN-212","OGN-213","OGN-214","OGN-215","OGN-216","OGN-217","OGN-218","OGN-219","OGN-271","OGN-272","OGN-273","OGN-274"}
OGN_Uncommon_Pool = {"OGN-015","OGN-016","OGN-017","OGN-018","OGN-019","OGN-020","OGN-021","OGN-022","OGN-023","OGN-024","OGN-056","OGN-057","OGN-058","OGN-059","OGN-060","OGN-061","OGN-062","OGN-063","OGN-064","OGN-065","OGN-097","OGN-098","OGN-099","OGN-100","OGN-101","OGN-102","OGN-103","OGN-104","OGN-105","OGN-106","OGN-138","OGN-139","OGN-140","OGN-141","OGN-142","OGN-143","OGN-144","OGN-145","OGN-146","OGN-147","OGN-179","OGN-180","OGN-181","OGN-182","OGN-183","OGN-184","OGN-185","OGN-186","OGN-187","OGN-188","OGN-220","OGN-221","OGN-222","OGN-223","OGN-224","OGN-225","OGN-226","OGN-227","OGN-228","OGN-229","OGN-275","OGN-276","OGN-277","OGN-278","OGN-279","OGN-280","OGN-281","OGN-282","OGN-283","OGN-284","OGN-285","OGN-286","OGN-287","OGN-288","OGN-289","OGN-290","OGN-291","OGN-292","OGN-293","OGN-294","OGN-295","OGN-296","OGN-297","OGN-298"}
OGN_Rare_Pool = {"OGN-025","OGN-026","OGN-027","OGN-028","OGN-029","OGN-030","OGN-031","OGN-032","OGN-033","OGN-034","OGN-035","OGN-036","OGN-066","OGN-067","OGN-068","OGN-069","OGN-070","OGN-071","OGN-072","OGN-073","OGN-074","OGN-075","OGN-076","OGN-077","OGN-107","OGN-108","OGN-109","OGN-110","OGN-111","OGN-112","OGN-113","OGN-114","OGN-115","OGN-116","OGN-117","OGN-118","OGN-148","OGN-149","OGN-150","OGN-151","OGN-152","OGN-153","OGN-154","OGN-155","OGN-156","OGN-157","OGN-158","OGN-159","OGN-189","OGN-190","OGN-191","OGN-192","OGN-193","OGN-194","OGN-195","OGN-196","OGN-197","OGN-198","OGN-199","OGN-200","OGN-230","OGN-231","OGN-232","OGN-233","OGN-234","OGN-235","OGN-236","OGN-237","OGN-238","OGN-239","OGN-240","OGN-241","OGN-247","OGN-249","OGN-251","OGN-253","OGN-255","OGN-257","OGN-259","OGN-261","OGN-263","OGN-265","OGN-267","OGN-269"}
OGN_Epic_Pool = {"OGN-037","OGN-038","OGN-039","OGN-040","OGN-041","OGN-078","OGN-079","OGN-080","OGN-081","OGN-082","OGN-119","OGN-120","OGN-121","OGN-121a","OGN-122","OGN-123","OGN-160","OGN-161","OGN-162","OGN-163","OGN-164","OGN-201","OGN-202","OGN-203","OGN-204","OGN-205","OGN-242","OGN-243","OGN-244","OGN-245","OGN-246","OGN-248","OGN-250","OGN-252","OGN-254","OGN-256","OGN-258","OGN-260","OGN-262","OGN-264","OGN-266","OGN-268","OGN-270"}
OGN_Showcase_Pool = {"OGN-007a","OGN-027a","OGN-030a","OGN-039a","OGN-041a","OGN-042a","OGN-066a","OGN-076a","OGN-078a","OGN-079a","OGN-089a","OGN-112a","OGN-117a","OGN-119a","OGN-126a","OGN-151a","OGN-158a","OGN-162a","OGN-164a","OGN-166a","OGN-193a","OGN-197a","OGN-202a","OGN-205a","OGN-214a","OGN-238a","OGN-240a","OGN-243a","OGN-246a","OGN-299","OGN-299s","OGN-300","OGN-300s","OGN-301","OGN-301s","OGN-302","OGN-302s","OGN-303","OGN-303s","OGN-304","OGN-304s","OGN-305","OGN-305s","OGN-306","OGN-306s","OGN-307","OGN-307s","OGN-308","OGN-308s","OGN-309","OGN-309s","OGN-310","OGN-310s"}
OGN_RarePlus_Roll = { { pool = "OGN_Rare_Pool", weight = 87.5 }, { pool = "OGN_Epic_Pool", weight = 12.5 } }
OGN_Any_Roll = { { pool = "OGN_Common_Pool", weight = 75 }, { pool = "OGN_Uncommon_Pool", weight = 22 }, { pool = "OGN_Rare_Pool", weight = 2.5 }, { pool = "OGN_Epic_Pool", weight = 0.4 }, { pool = "OGN_Showcase_Pool", weight = 0.1 } }

UNL_Common_Pool = {"UNL-001","UNL-002","UNL-003","UNL-004","UNL-005","UNL-006","UNL-007","UNL-008","UNL-009","UNL-010","UNL-031","UNL-032","UNL-033","UNL-034","UNL-035","UNL-036","UNL-037","UNL-038","UNL-039","UNL-040","UNL-061","UNL-062","UNL-063","UNL-064","UNL-065","UNL-066","UNL-067","UNL-068","UNL-069","UNL-070","UNL-091","UNL-092","UNL-093","UNL-094","UNL-095","UNL-096","UNL-097","UNL-098","UNL-099","UNL-100","UNL-121","UNL-122","UNL-123","UNL-124","UNL-125","UNL-126","UNL-127","UNL-128","UNL-129","UNL-130","UNL-151","UNL-152","UNL-153","UNL-154","UNL-155","UNL-156","UNL-157","UNL-158","UNL-159","UNL-160"}
UNL_Uncommon_Pool = {"UNL-011","UNL-012","UNL-013","UNL-014","UNL-015","UNL-016","UNL-017","UNL-018","UNL-041","UNL-042","UNL-043","UNL-044","UNL-045","UNL-046","UNL-047","UNL-048","UNL-071","UNL-072","UNL-073","UNL-074","UNL-075","UNL-076","UNL-077","UNL-078","UNL-101","UNL-102","UNL-103","UNL-104","UNL-105","UNL-106","UNL-107","UNL-108","UNL-131","UNL-132","UNL-133","UNL-134","UNL-135","UNL-136","UNL-137","UNL-138","UNL-161","UNL-162","UNL-163","UNL-164","UNL-165","UNL-166","UNL-167","UNL-168","UNL-205","UNL-206","UNL-207","UNL-208","UNL-209","UNL-210","UNL-211","UNL-212","UNL-213","UNL-214","UNL-215","UNL-216","UNL-217","UNL-218","UNL-219"}
UNL_Rare_Pool = {"UNL-019","UNL-020","UNL-021","UNL-022","UNL-023","UNL-024","UNL-025","UNL-026","UNL-049","UNL-050","UNL-051","UNL-052","UNL-053","UNL-054","UNL-055","UNL-056","UNL-079","UNL-080","UNL-081","UNL-082","UNL-083","UNL-084","UNL-085","UNL-086","UNL-109","UNL-110","UNL-111","UNL-112","UNL-113","UNL-114","UNL-115","UNL-116","UNL-139","UNL-140","UNL-141","UNL-142","UNL-143","UNL-144","UNL-145","UNL-146","UNL-169","UNL-170","UNL-171","UNL-172","UNL-173","UNL-174","UNL-175","UNL-176","UNL-181","UNL-183","UNL-185","UNL-187","UNL-189","UNL-191","UNL-193","UNL-195","UNL-197","UNL-199","UNL-201","UNL-203"}
UNL_Epic_Pool = {"UNL-027","UNL-028","UNL-029","UNL-030","UNL-057","UNL-058","UNL-059","UNL-060","UNL-087","UNL-088","UNL-089","UNL-090","UNL-117","UNL-118","UNL-119","UNL-120","UNL-147","UNL-148","UNL-149","UNL-150","UNL-177","UNL-178","UNL-179","UNL-180","UNL-182","UNL-184","UNL-186","UNL-188","UNL-190","UNL-192","UNL-194","UNL-196","UNL-198","UNL-200","UNL-202","UNL-204"}
UNL_Showcase_Pool = {"UNL-022a","UNL-024a","UNL-028a","UNL-029a","UNL-030a","UNL-051a","UNL-055a","UNL-058a","UNL-059a","UNL-060a","UNL-079a","UNL-082a","UNL-087a","UNL-089a","UNL-090a","UNL-113a","UNL-116a","UNL-118a","UNL-119a","UNL-120a","UNL-143a","UNL-145a","UNL-147a","UNL-149a","UNL-150a","UNL-172a","UNL-176a","UNL-177a","UNL-178a","UNL-179a","UNL-220","UNL-221","UNL-222","UNL-223","UNL-224","UNL-225","UNL-226","UNL-226s","UNL-227","UNL-227s","UNL-228","UNL-228s","UNL-229","UNL-229s","UNL-230","UNL-230s","UNL-231","UNL-231s","UNL-232","UNL-232s","UNL-233","UNL-233s","UNL-234","UNL-234s","UNL-235","UNL-235s","UNL-236","UNL-236s","UNL-237","UNL-237s","UNL-238"}
UNL_RarePlus_Roll = { { pool = "UNL_Rare_Pool", weight = 87.5 }, { pool = "UNL_Epic_Pool", weight = 12.5 } }
UNL_Any_Roll = { { pool = "UNL_Common_Pool", weight = 75 }, { pool = "UNL_Uncommon_Pool", weight = 22 }, { pool = "UNL_Rare_Pool", weight = 2.5 }, { pool = "UNL_Epic_Pool", weight = 0.4 }, { pool = "UNL_Showcase_Pool", weight = 0.1 } }

pack_collations = {
  SFD = {
    { type = "SFD_Common_Pool", count = 7 },
    { type = "SFD_Uncommon_Pool", count = 3 },
    { type = "SFD_RarePlus_Roll", count = 2 },
    { type = "SFD_Any_Roll", count = 1 },
  },
  OGN = {
    { type = "OGN_Common_Pool", count = 7 },
    { type = "OGN_Uncommon_Pool", count = 3 },
    { type = "OGN_RarePlus_Roll", count = 2 },
    { type = "OGN_Any_Roll", count = 1 },
  },
  UNL = {
    { type = "UNL_Common_Pool", count = 7 },
    { type = "UNL_Uncommon_Pool", count = 3 },
    { type = "UNL_RarePlus_Roll", count = 2 },
    { type = "UNL_Any_Roll", count = 1 },
  },
}

-- Counts: SFD C/U/R/E/S = 61/62/59/39/66
-- Counts: OGN C/U/R/E/S = 88/84/84/43/53
-- Counts: UNL C/U/R/E/S = 60/63/60/36/61

-- =========================
-- Utility
-- =========================

function randomFromPool(pool, used)
  if not pool or #pool == 0 then return nil end

  local attempts = 0
  while attempts < 50 do
    local card = pool[math.random(#pool)]
    if not used[card] then
      return card
    end
    attempts = attempts + 1
  end

  return nil
end

function weightedRoll(rollTable, used)
  local total = 0
  for _, entry in ipairs(rollTable) do
    total = total + entry.weight
  end

  local attempts = 0
  while attempts < 50 do
    local roll = math.random() * total
    local running = 0

    for _, entry in ipairs(rollTable) do
      running = running + entry.weight
      if roll <= running then
        local pool = _G[entry.pool]
        local card = randomFromPool(pool, used)
        if card then return card end
        break
      end
    end

    attempts = attempts + 1
  end

  return nil
end

-- =========================
-- Pack Generation
-- =========================

function GeneratePack(set_id)
  local collation = pack_collations[set_id]
  if not collation then
    print("Unknown set:", set_id)
    return {}
  end

  local card_list = {}
  local used = {}

  for _, entry in ipairs(collation) do
    for i = 1, entry.count do
      local card

      if entry.type:find("_Roll") then
        card = weightedRoll(_G[entry.type], used)
      else
        card = randomFromPool(_G[entry.type], used)
      end

      if card then
        used[card] = true
        table.insert(card_list, card)
      else
        print("Warning: Could not find unique card for", entry.type)
      end
    end
  end

  return card_list
end

-- =========================
-- TTS Hook
-- =========================

function onLoad(saved_data)
  Global.setVar("Riftbound_CollationLibrary", self)
end
